from datetime import datetime

from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin


db = SQLAlchemy()


# ============================================================
# USER
# ============================================================

class User(db.Model, UserMixin):

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    username = db.Column(
        db.String(100),
        unique=True,
        nullable=False
    )

    email = db.Column(
        db.String(120),
        unique=True,
        nullable=False
    )

    # Nullable because Google users may not have a password
    password = db.Column(
        db.String(200),
        nullable=True
    )

    is_admin = db.Column(
        db.Boolean,
        default=False
    )

    google_id = db.Column(
        db.String(100),
        unique=True,
        nullable=True
    )

    profile_picture = db.Column(
        db.String(300),
        nullable=True
    )

    # ========================================================
    # INVITATION CAMPAIGN
    # ========================================================

    # Permanent invitation code belonging to this user.
    #
    # Example:
    # MZ-AB12CD
    #
    # The code will not change.
    invitation_code = db.Column(
        db.String(30),
        unique=True,
        nullable=True
    )

    # ID of the user who invited this user.
    #
    # NULL means the user joined without an inviter.
    #
    # Example:
    #
    # User A
    # id = 1
    #
    # User B
    # invited_by_id = 1
    #
    invited_by_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'user.id',
            ondelete='SET NULL'
        ),
        nullable=True
    )

    # When the account was created.
    #
    # This is used for the 10-day invitation-code
    # entry restriction.
    registered_at = db.Column(
        db.DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    # --------------------------------------------------------
    # USER WHO INVITED THIS USER
    # --------------------------------------------------------

    inviter = db.relationship(
        'User',
        remote_side=[id],
        foreign_keys=[invited_by_id],
        backref=db.backref(
            'invited_users',
            lazy=True
        )
    )

    # --------------------------------------------------------
    # USER PURCHASES
    # --------------------------------------------------------

    purchases = db.relationship(
        'Purchase',
        backref='user',
        lazy=True,
        cascade='all, delete-orphan'
    )

    # --------------------------------------------------------
    # REFERRAL PURCHASES GENERATED BY THIS USER'S INVITEES
    # --------------------------------------------------------

    referral_purchases = db.relationship(
        'ReferralPurchase',
        foreign_keys='ReferralPurchase.inviter_id',
        backref='inviter',
        lazy=True,
        cascade='all, delete-orphan'
    )

    # --------------------------------------------------------
    # REWARDS EARNED BY THIS USER
    # --------------------------------------------------------

    rewards = db.relationship(
        'Reward',
        foreign_keys='Reward.user_id',
        backref='user',
        lazy=True,
        cascade='all, delete-orphan'
    )

    # --------------------------------------------------------
    # AVAILABLE REWARD COUNT
    # --------------------------------------------------------

    def available_rewards(self):

        """
        Return the number of unused free rewards
        currently available to this user.
        """

        return Reward.query.filter_by(
            user_id=self.id,
            status='Available'
        ).count()


# ============================================================
# VIDEO / SINGLE MOVIE
# ============================================================

class Video(db.Model):

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    video_path = db.Column(
        db.String(300)
    )

    thumbnail = db.Column(
        db.String(300)
    )

    title = db.Column(
        db.String(50),
        nullable=False
    )

    # --------------------------------------------------------
    # FREE / PAID
    # --------------------------------------------------------
    # True  = Free movie
    # False = Paid movie

    free = db.Column(
        db.Boolean,
        default=False
    )

    # --------------------------------------------------------
    # MOVIE PRICE
    # --------------------------------------------------------
    # Default paid movie price = 1,000 TSh

    price = db.Column(
        db.Numeric(10, 2),
        default=1000.00,
        nullable=False
    )

    date_posted = db.Column(
        db.DateTime,
        default=datetime.utcnow
    )

    # --------------------------------------------------------
    # MOVIE PURCHASES
    # --------------------------------------------------------

    purchases = db.relationship(
        'Purchase',
        backref='video',
        lazy=True
    )


# ============================================================
# SERIES
# ============================================================

class Series(db.Model):

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    title = db.Column(
        db.String(100),
        nullable=False
    )

    description = db.Column(
        db.Text
    )

    # --------------------------------------------------------
    # FREE / PAID
    # --------------------------------------------------------
    # True  = Free series
    # False = Paid series

    free = db.Column(
        db.Boolean,
        default=False
    )

    # --------------------------------------------------------
    # SERIES PRICE
    # --------------------------------------------------------
    # Default paid series price = 2,000 TSh

    price = db.Column(
        db.Numeric(10, 2),
        default=2000.00,
        nullable=False
    )

    thumbnail = db.Column(
        db.String(300)
    )

    created_at = db.Column(
        db.DateTime,
        default=db.func.current_timestamp()
    )

    date_posted = db.Column(
        db.DateTime,
        default=datetime.utcnow
    )

    # --------------------------------------------------------
    # EPISODES
    # --------------------------------------------------------

    episodes = db.relationship(
        'Episode',
        backref='series',
        cascade='all, delete-orphan',
        lazy=True
    )

    # --------------------------------------------------------
    # SERIES PURCHASES
    # --------------------------------------------------------

    purchases = db.relationship(
        'Purchase',
        backref='series',
        lazy=True
    )


# ============================================================
# EPISODE
# ============================================================

class Episode(db.Model):

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    title = db.Column(
        db.String(100),
        nullable=False
    )

    episode_number = db.Column(
        db.Integer,
        nullable=False
    )

    video_path = db.Column(
        db.String(300)
    )

    series_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'series.id',
            ondelete='CASCADE'
        ),
        nullable=False
    )

    created_at = db.Column(
        db.DateTime,
        default=db.func.current_timestamp()
    )


# ============================================================
# PURCHASE
# ============================================================

class Purchase(db.Model):

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    # --------------------------------------------------------
    # USER
    # --------------------------------------------------------

    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id'),
        nullable=False
    )

    # --------------------------------------------------------
    # MOVIE
    # --------------------------------------------------------
    # NULL when purchase is for a series

    video_id = db.Column(
        db.Integer,
        db.ForeignKey('video.id'),
        nullable=True
    )

    # --------------------------------------------------------
    # SERIES
    # --------------------------------------------------------
    # NULL when purchase is for a movie

    series_id = db.Column(
        db.Integer,
        db.ForeignKey('series.id'),
        nullable=True
    )

    # --------------------------------------------------------
    # ITEM TYPE
    # --------------------------------------------------------
    # "movie" or "series"

    item_type = db.Column(
        db.String(20),
        nullable=False
    )

    # --------------------------------------------------------
    # AMOUNT PAID
    # --------------------------------------------------------
    #
    # Normal purchase:
    # Movie  = 1000
    # Series = 2000
    #
    # Reward purchase:
    # amount = 0

    amount = db.Column(
        db.Numeric(10, 2),
        nullable=False
    )

    # --------------------------------------------------------
    # MERCHANT REFERENCE
    # --------------------------------------------------------
    # Unique reference sent to Pesapal

    merchant_reference = db.Column(
        db.String(100),
        nullable=False,
        unique=True
    )

    # --------------------------------------------------------
    # PESAPAL TRACKING ID
    # --------------------------------------------------------

    order_tracking_id = db.Column(
        db.String(100),
        nullable=True
    )

    # --------------------------------------------------------
    # PAYMENT STATUS
    # --------------------------------------------------------
    #
    # Pending
    # Completed
    # Failed
    # etc.

    payment_status = db.Column(
        db.String(30),
        default='Pending',
        nullable=False
    )

    # --------------------------------------------------------
    # PURCHASE DATE
    # --------------------------------------------------------

    purchased_at = db.Column(
        db.DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    # --------------------------------------------------------
    # ACCESS EXPIRATION
    # --------------------------------------------------------
    #
    # Both movies and series have 30 days of access.
    #
    # The actual 30-day period is calculated in payment.py
    # when Pesapal confirms the payment.

    expires_at = db.Column(
        db.DateTime,
        nullable=True
    )

    # --------------------------------------------------------
    # CHECK ACTIVE PURCHASE
    # --------------------------------------------------------

    def is_active(self):

        """
        Returns True if this purchase:

        1. Was successfully completed
        2. Has an expiration date
        3. Has not expired yet
        """

        return (
            self.payment_status == 'Completed'
            and
            self.expires_at is not None
            and
            self.expires_at > datetime.utcnow()
        )


# ============================================================
# REFERRAL PURCHASE
# ============================================================

class ReferralPurchase(db.Model):

    """
    Records a qualifying purchase made by an invited user.

    Example:

    User A invites User B.

    User B buys a movie.

    A ReferralPurchase record is created:

        inviter_id     = User A
        invited_user_id = User B
        purchase_id    = B's purchase

    This allows us to calculate rewards safely.
    """

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    # --------------------------------------------------------
    # INVITER
    # --------------------------------------------------------
    # User who will receive credit for this purchase.

    inviter_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'user.id',
            ondelete='CASCADE'
        ),
        nullable=False
    )

    # --------------------------------------------------------
    # INVITED USER
    # --------------------------------------------------------
    # User who actually made the purchase.

    invited_user_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'user.id',
            ondelete='CASCADE'
        ),
        nullable=False
    )

    # --------------------------------------------------------
    # PURCHASE
    # --------------------------------------------------------
    # The completed purchase that generated this
    # referral credit.

    purchase_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'purchase.id',
            ondelete='CASCADE'
        ),
        nullable=False,
        unique=True
    )

    # --------------------------------------------------------
    # CREATED DATE
    # --------------------------------------------------------

    created_at = db.Column(
        db.DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    # --------------------------------------------------------
    # RELATIONSHIPS
    # --------------------------------------------------------

    invited_user = db.relationship(
        'User',
        foreign_keys=[invited_user_id],
        backref=db.backref(
            'referral_purchase_records',
            lazy=True
        )
    )

    purchase = db.relationship(
        'Purchase',
        backref=db.backref(
            'referral_purchase',
            uselist=False
        )
    )


# ============================================================
# REWARD
# ============================================================

class Reward(db.Model):

    """
    One free reward earned by an inviter.

    Every 3 qualifying purchases made by the
    inviter's invited users creates ONE Reward.

    Example:

        3 purchases  -> 1 reward
        6 purchases  -> 2 rewards
        9 purchases  -> 3 rewards

    Each reward is stored individually.

    When the user redeems one reward:

        Available -> Used

    This means the user's reward balance decreases
    by exactly 1.
    """

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    # --------------------------------------------------------
    # REWARD OWNER
    # --------------------------------------------------------

    user_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'user.id',
            ondelete='CASCADE'
        ),
        nullable=False
    )

    # --------------------------------------------------------
    # REWARD STATUS
    # --------------------------------------------------------
    #
    # Available = can be used
    # Used      = already redeemed

    status = db.Column(
        db.String(20),
        default='Available',
        nullable=False
    )

    # --------------------------------------------------------
    # WHEN REWARD WAS CREATED
    # --------------------------------------------------------

    created_at = db.Column(
        db.DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    # --------------------------------------------------------
    # WHEN REWARD WAS USED
    # --------------------------------------------------------

    used_at = db.Column(
        db.DateTime,
        nullable=True
    )

    # --------------------------------------------------------
    # WHAT PURCHASE USED THIS REWARD
    # --------------------------------------------------------
    #
    # This will point to the free Purchase created when
    # the reward is redeemed.
    #
    # Nullable because the reward is initially unused.

    used_purchase_id = db.Column(
        db.Integer,
        db.ForeignKey(
            'purchase.id',
            ondelete='SET NULL'
        ),
        nullable=True,
        unique=True
    )

    # --------------------------------------------------------
    # RELATIONSHIP TO REDEMPTION PURCHASE
    # --------------------------------------------------------

    used_purchase = db.relationship(
        'Purchase',
        foreign_keys=[used_purchase_id],
        backref=db.backref(
            'reward_used',
            uselist=False
        )
    )

    # --------------------------------------------------------
    # CHECK IF AVAILABLE
    # --------------------------------------------------------

    def is_available(self):

        return self.status == 'Available'
